# app.yaml
runtime: nodejs20 # or another supported version

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  DB_USER: "admin"
  DB_PASSWORD: "1TrO0LCHubSi"
  DB_HOST: "ep-cold-boat-a5hnkt7t.us-east-2.aws.neon.tech/videogames?sslmode=require"
  DB_NAME: "videogames"
  DB_PORT: "5432"
  API_KEY: "a17ca2f5abf4430a9d6e631d3f61734f"
  FRONT_URL: "https://henry-games.vercel.app"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
